import mysql.connector as sql
conn= sql.connect(host='localhost', user = 'root', password ='luv@dec4')
c1=conn.cursor()
c1.execute("create database account")
c1.execute('use account')
c1.execute("create table stock (product_no int(10) primary key,product_name varchar(30),cost_per_product int(10),stock int(10),purchased int(10) );")
c1.execute("create table user(username varchar(255),passwd varchar(255));")
c1.execute("insert into stock values(1,'Nestle-Maggi',30,100,0);")
c1.execute("insert into stock values(2,'Amul-Butter',25,70,0);")
c1.execute("insert into stock values(3,'Bread',25,100,0);")
c1.execute("insert into stock values(4,'Oreo Biscuits',40,100,0);")
c1.execute("insert into stock values(5,'Salt',15,100,0);")
c1.execute("insert into stock values(6,'Tomato Ketchup',30,100,0);")
c1.execute("insert into stock values(7,'Nestle-Coffee',65,100,0);")
c1.execute("insert into stock values(8,'Popcorn',10,100,0);")
c1.execute("insert into stock values(9,'Pepsi',45,100,0);")
conn.commit()
